import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Banner from "@/components/Banner";
import Navbar from "@/components/Navbar";
import { Fade, Slide, Zoom } from "react-awesome-reveal";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-noto-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={`${notoSans.variable} h-full antialiased font-sans`}
    >
      <body className="min-h-full flex flex-col relative">
        <div className="absolute inset-0 -z-10 bg-[url('/pleca.png')] bg-cover bg-no-repeat opacity-30"></div>

        {/* Banner fuera de cualquier animación */}
        <Banner />
        <Fade>
          <main className="flex-grow relative z-10 flex flex-col pt-36">
            <Navbar />
            {children}
          </main>
        </Fade>
      </body>
    </html>
  );
}